version: 2.1

jobs:
  ## pre build jobs
  service1-pre-build-app:
    executor: openjdk
    working_directory: ~/project/services/service1
    steps:
      - checkout:
          path: ~/project
      - test_and_analyze
  service1-pre-build-docker:
    executor: openjdk
    working_directory: ~/project/services/service1
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - dockerfile_analyze
  ## build jobs
  service1-build-and-push:
    executor: openjdk
    working_directory: ~/project/services/service1
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - gcloud_setting
      - check-image-existence
      - image_build
      - image_push
  ## deploy jobs
  service1-deploy:
    executor: openjdk
    working_directory: ~/project/services/service1
    steps:
      - checkout:
          path: ~/project
      - sample-cmd # 仮コマンド

workflows:
  service1:
    jobs:
      - service1-pre-build-app: 
          context: 
            - SonarCloud
            - GoogleCloud
      - service1-pre-build-docker:
          context:
            - GoogleCloud
      - service1-build-and-push:
          context:
            - GoogleCloud
          requires:
            - service1-pre-build-app
            - service1-pre-build-docker
          filters:
            branches:
              only: main
      - service1-deploy:
          context:
            - GoogleCloud
          requires:
            - service1-build-and-push
